a = 8
b = 3
c = a + b
print("a + b = ", c)
c = a - b
print("a - b = ", c)
c = a * b
print("a * b = ", c)
c = a / b
print("a / b = ", c)
c = a // b
print("a // b = ", c)
c = a % b
print("a % b = ", c)
c = a ** 2
print("a ** 2 = ", c)
c = a ** 0.5
print("a ** 0.5 = ", c)